version: '3.8'

services:
  app:
    build:
      context: ./core
      dockerfile: Dockerfile
    restart: always
    command: gunicorn gallery.wsgi:application -c "python:config.gunicorn"
    volumes:
      - ./core/logs/:/usr/src/app/core/logs
      - ./core/staticfiles/:/usr/src/app/core/staticfiles/
      - ./data:/usr/src/app/data
    expose:
      - 80
    env_file:
      - ./.env
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork

  db:
    image: postgres:12
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - djangonetwork
    env_file:
      - ./.env.db

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - ./core/staticfiles/:/usr/src/app/core/staticfiles/
      - ./data:/usr/src/app/data
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - djangonetwork

volumes:
  postgres_data:


networks:
  djangonetwork:
    driver: bridge
